### ISSUE TITLE
How to set dataset directory

### ISSUE THREAD

**Issue by xuhui1994** [mahmoudnafifi/Deep_White_Balance#1]

**Comment by xuhui1994** [comment]
Sorry.I need someone help. I wanna to run this program.But Given so many datasets and I dont know what datasets I should download.After downloading this necessary datasets,How to set directory.

**Comment by mahmoudnafifi** [comment]
You don’t need to download any datasets to run this program. Unless you want to re-train the models, you can use Set1 for training. 

As explained in the readme file, you should copy both input images and ground-truth images in a single directory. Each pair of input/ground truth images should be in the following format: input image: name_WB_picStyle.png and the corresponding ground truth image: name_G_AS.png. This is the same filename style used in the Rendered WB dataset. As an example, please refer to dataset directory.

For Matlab:
You should adjust training image directories from the datasetDir variable before running the code. You can change the training settings in training.m before training.

For PyTorch:
You can set the dataset directory using --training_dir 
Example: CUDA_VISIBLE_DEVICE=0 python train.py --training_dir ../dataset/
