### ISSUE TITLE
About mapping_func

### ISSUE THREAD

**Issue by YangGangZhiQi** [mahmoudnafifi/Deep_White_Balance#12]
Hi, thanks for this great works. After reading the source codes, I am curious about the role of get_mapping_func in deepWB.py.  
![deepWB_map](https://user-images.githubusercontent.com/87355944/209771562-b0136de3-21a6-43a4-ba55-ac49b335f1f3.png)
Why do we have to get mapping from image_resized to output_awb first and calculate the output of image? Why donot we calculate output of image directly?

**Comment by mahmoudnafifi** [comment]
Hi,
There are couple of reasons, including the performance with high res images. We discussed this point in detail in Sec 2.5 of the paper.

**Comment by YangGangZhiQi** [comment]
Get it! Thanks for your quick reply and detailed explanation in Sec2.5.  Thanks again for this good jobs.
