### ISSUE TITLE
how to train your model on set2 or cube+ dataset?

### ISSUE THREAD

**Issue by TengFeiHan0** [mahmoudnafifi/Deep_White_Balance#3]
after checking your code, I find that your dataloader is only suitable to set1, but set1 consists of a large amount of dataset. I want to train your model on set2 or cube+, but I didn't the corresponding dataloader

**Comment by TengFeiHan0** [comment]
@xuhui1994 你是怎么做的？方便交流一下吗？

**Comment by xuhui1994** [comment]
加微信xh978188311,交流一下





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tengfei han"<notifications@github.com&gt;; 
发送时间: 2020年9月7日(星期一) 下午5:26
收件人: "mahmoudnafifi/Deep_White_Balance"<Deep_White_Balance@noreply.github.com&gt;; 
抄送: "威爵"<978188311@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [mahmoudnafifi/Deep_White_Balance] how to train your model on set2 or cube+ dataset? (#3)





 
@xuhui1994 你是怎么做的？方便交流一下吗？

**Comment by mahmoudnafifi** [comment]
@TengFeiHan0 Yes, the code is only provided for training on set1 with the augmented set. But, you can do some steps to make it works for other sets. You first need to copy all input/gt images into a single directory, such that for each image there are three ground-truth images with the same name but end with the following parts: 'G_AS.png', 'T_AS.png', 'S_AS.png' (for AWB, Shade WB, Tungsten WB ground-truth, respectively). Other input images should also follow the same style; i.e., imagename_A_B.png, here A and B can be random characters or (as we have in Set1) it can be the WB settings, and picture style, respectively. 
Then, use fold=0 and the training should start without any problem.

**Comment by mahmoudnafifi** [comment]
@xuhui1994 if you have any questions, please let me know .. but in English please :).

**Comment by TengFeiHan0** [comment]
@mahmoudnafifi I have downloaded your WB dataset, but I failed to unzip it correctly. The command I used is `cat Set1_input_images.z* > wb.zip && unzip wb.zip`,after this I only got about 10000 images. I guess there have some problem when unzipping these files. If possible, would you mind providing a single link to the Set1 dataset rather than so many parts? Or how did you unzip your files under the Linux system?

**Comment by mahmoudnafifi** [comment]
I will find a way of uploading them in a single zip file and back to you soon.

**Comment by TengFeiHan0** [comment]
@mahmoudnafifi ok, thank you for help. I'm waiting for you. By the way, for set2 or cube+ dataset, there don't have the corresponding gt images end with `('G_AS.png', 'T_AS.png', 'S_AS.png')`, how did you generate it?

**Comment by mahmoudnafifi** [comment]
@TengFeiHan0 Yes, you need either to rename Cube+'s ground truth images to end with G_AS.png or maybe change the code. 
One more thing, not all images in Set1 have ground-truth of T and S white-balance settings with the Adobe Standard (AS) picture style. So, you need to add a piece of code to select only those images that have ground-truth. Please, check this [comment](https://github.com/mahmoudnafifi/WB_sRGB/issues/2#issuecomment-689242755).

Update: I have uploaded Set 1 as a single zip file. Check it from [here](https://github.com/mahmoudnafifi/WB_sRGB/blob/master/README.md) or [here](http://cvil.eecs.yorku.ca/projects/public_html/sRGB_WB_correction/dataset.html).
