### ISSUE TITLE
about using deep white balance in video files?

### ISSUE THREAD

**Issue by zelenooki87** [mahmoudnafifi/Deep_White_Balance#6]
Hi. Thank you for great work and published code for free to public.
I am using your code in Matlab. GUI preview is great addition.
I want ask you, could you modify code to support video files? It would be easier than manually extract frames and merging sequence.
Thank you in advance!

**Comment by mahmoudnafifi** [comment]
Thanks for the suggestion. Sadly, I don't have time to do it. Contributions are welcomed.
