### ISSUE TITLE
Evaluation metrics

### ISSUE THREAD

**Issue by guozonghui** [mahmoudnafifi/Deep_White_Balance#9]
We evaluate the results of the pre-trained model on the Set 2, but it is inconsistent with the results of the paper. Our results: DeltaE 2000 mean: 5.28, MSE mean= 138.94, MAE mean= 4.35. The evaluation algorithm is referenced from [WB_sRGB](https://github.com/mahmoudnafifi/WB_sRGB/tree/master/WB_sRGB_Python).
I would like to know what is causing this deviation, and could you release the evaluation method?
Thanks!

`awb_gt = cv2.imread(awb_path, cv2.IMREAD_COLOR)`
`file_name = os.path.basename(awb_path).replace(".png", "_AWB.png")`
`awb = cv2.imread(opt.result_root+file_name, cv2.IMREAD_COLOR)`
`deltaE00, MSE, MAE = evaluate_cc(awb, awb_gt, metadata["cc_mask_area"], opt=3)`

**Comment by mahmoudnafifi** [comment]
Thanks for your message. It seems to me that you use the pytorch version. If so, as mentioned in readme, there is no guarantee that the trained models produce exactly the same results. Matlab code should produce the same results reported in the paper. 

And yes, the evaluation code in https://github.com/mahmoudnafifi/WB_sRGB/ is what we used for evaluation in this paper too.

**Comment by guozonghui** [comment]
OK, I got it. Thank you very much!
